docker run -p 6688:6688 -v ~/.chainlink-rinkeby:/chainlink -it 
--env-file=.env smartcontract/chainlink:<version> local n


version: '3.8'
services:
  openethereum-rinkeby:
    image: smartcontract/chainlink:1.0.1-nonroot
    entrypoint:
      - chainlink
      - node
      - start

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /chainlink/:/chainlink/:rw
    ports:
    - "6688:6688"
    restart: unless-stopped
    stop_grace_period: 180s
    networks:
      host_network:

networks:
  host_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
